import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutHeader from "@/components/LayoutHeader";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="">
        <LayoutHeader className="fixed top-0 z-50" />
        <main className="mt-header-height">
          {children}
        </main>
        <footer className=" text-white">
          <div className="bg-black p-10">
            <h2>FIND OUT MORE ABOUT EARTH CAFE</h2>
            <div className="grid grid-cols-3 gap-10">
              <nav className="flex flex-col gap-2">
                <Link href="">However Link</Link>
                <Link href="">However Link</Link>
                <Link href="">However Link</Link>
              </nav>
              <nav className="flex flex-col gap-2">
                <Link href="">link there</Link>
                <Link href="">link there</Link>
                <Link href="">link there</Link>
              </nav>
              <nav className="flex flex-col gap-2">
                <Link href="">That link</Link>
                <Link href="">That link</Link>
                <Link href="">That link</Link>
              </nav>
            </div>
          </div>
          <div className="bg-neutral-800 p-10">
            Privacy Policy Terms & Conditions (Updated) CA Supply Chain Act Accessibility Statement
            © 2026 Earth Restaurant Group. All right reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
